name: clang-tidy
description: run clang-tidy
inputs:
  source_directory:
    description: directory of the project source files
    required: true
  build_directory:
    description: project build directory
    required: true

runs:
  using: composite
  steps:
    - name: check
      shell: bash
      run: |
        if ! (clang-tidy --version); then
          log error "clang-tidy not installed"
          exit 1
        fi
    - name: clang-tidy
      shell: bash
      env:
        SOURCE_DIR: ${{ inputs.source_directory }}
        BUILD_DIR: ${{ inputs.build_directory }}
      run: |
        ${{ github.action_path }}/action.sh "${SOURCE_DIR}" "${BUILD_DIR}"
