---
name: Export 1Password secrets
description: Export 1Password secrets to environment variables

inputs:
  vault:
    description: 1Password vault
    required: true
  item:
    description: 1Password item
    required: true
  token:
    description: 1Password API token
    required: true
  sections:
    description: 1Password item section
    default: ''
    required: false
  export_variables:
    description: export secrets to environment variables
    default: 'true'
    required: false
  create_env_file:
    description: create a .env file with the secrets
    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - name: install 1Password cli
      uses: 1Password/install-cli-action@v2.0.1

    - name: export secrets
      shell: bash
      env:
        OP_VAULT: ${{ inputs.vault }}
        OP_ITEM: ${{ inputs.item }}
        OP_TOKEN: ${{ inputs.token }}
        OP_SECTIONS: ${{ inputs.sections }}
        EXPORT_VARIABLES: ${{ inputs.export_variables }}
        CREATE_ENV_FILE: ${{ inputs.create_env_file }}
      run: |
        ./action.sh
